# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4b0fb4773404f11f479d491ebd3f49edcf0b218d2d3d0aad709d14a77c8e700c94d397011e62831c8bf89b06cab05870f8842cbb95d40aa51b636e618a3d875

test:
  secret_key_base: 66f5f189e241f1cc752b97ccc770b609c041b0387c170ff3965ac17f88d81a80f8415d8409a9adefaf80c0419d38481cebfe5bb5d0b2a8f1485281c0c8510347

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
